apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fuel-service-hpa
  namespace: fuel-monitor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fuel-service
  minReplicas: 1
  maxReplicas: 9
  metrics:
  - type: External
    external:
      metric:
        name: kafka_consumergroup_lag
      target:
        type: AverageValue
        averageValue: "1000"
  - type: External
    external:
      metric:
        name: fuel_monitor_predicted_rps
      target:
        type: AverageValue
        averageValue: "50"
