apiVersion: v1
kind: Service
metadata:
  name: fuel-service
  namespace: fuel-monitor
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fuel-service
